server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true
    username: self
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:  classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml